#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER docker;
    CREATE DATABASE docker;
    GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
EOSQL

cd "/opt/json-to-xls/build/install/json-to-xls/"
ln -s "/opt/json-to-xls/build/install/json-to-xls/api.txt" "./api.txt "
"./bin/json-to-xls" db migrate json-to-xls.yml
"./bin/json-to-xls" server json-to-xls.yml