#!/bin/bash

cd /opt/json-to-xls/build/install/json-to-xls/
ln -s /opt/json-to-xls/build/install/json-to-xls/api.txt ./api.txt 
./bin/json-to-xls db migrate json-to-xls.yml
./bin/json-to-xls server json-to-xls.yml